Repository ultralytics/.github, pull requests merged in 2025-03, with the labels that each got.

#64 Create .gitignore
  .gitignore
Labels: devops

#65 Update
  CODE_OF_CONDUCT.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  SECURITY.md
  profile/README.md
Labels: documentation, enhancement, devops

#66 Update SECURITY.md
  SECURITY.md
Labels: documentation

#67 Ultralytics Refactor https://ultralytics.com/actions
  CODE_OF_CONDUCT.md
  README.md
  profile/README.md
Labels: documentation, enhancement
